# SPDX-FileCopyrightText: 2024 Samsung Electronics Co., Ltd
#
# SPDX-License-Identifier: BSD-3-Clause

---
name: Release

on:
  push:
    tags:
      - 'v*'       # Only trigger when a tag starting with 'v' is pushed

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch python build artifact
        uses: actions/download-artifact@v3
        with:
          name: python-build-artifacts

      - name: Checkout the repository
        uses: actions/checkout@v3.1.0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v1

      - name: Upload Release to PyPI
        run: |
          echo "Uploading source code"
          nix develop --command python -m twine upload --verbose --non-interactive --skip-existing -u '__token__' -p ${{ secrets.PYPI_API_TOKEN }} dist/*