---
name: Tests

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
    branches:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: pytests
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    - name: Set PIPX_DEFAULT_PYTHON
      run: |
        echo "PIPX_DEFAULT_PYTHON=$(which python3)" >> $GITHUB_ENV

    - name: git checkout
      uses: actions/checkout@v4

    - name: Fetch python build artifact
      uses: actions/download-artifact@v2
      with:
        name: python-build-artifacts

    - name: build and install
      run: |
        make install

    - name: run checks
      run: |
        make check

    - name: run tests
      run: |
        make tests
